apiVersion: apps/v1
# object type
kind: Deployment
metadata:
  # name of the deployment
  name: client-deployment
spec:
  # 3 pods running
  replicas: 3
  selector:
    # component is managing the web (frontend)
    # matchlabels component need to match template.metadata.labels.component value.
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
